### ISSUE TITLE
Cannot use the "file" loader without an output path

### ISSUE THREAD

**Issue by silveltman** [CloudCannon/bookshop#174]
I'm getting the following error:
```
silveltman@Sils-MBP library % npx @bookshop/browser
📚 Looking for Bookshop component libraries...
📚 —— Loading Bookshop from ./src
 > error: Cannot use the "file" loader without an output path

/Users/silveltman/Documents/Github/monorepo-astro/library/node_modules/@bookshop/builder/node_modules/esbuild/lib/main.js:1493
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
error: Cannot use the "file" loader without an output path
    at failureErrorWithLog (/Users/silveltman/Documents/Github/monorepo-astro/library/node_modules/@bookshop/builder/node_modules/esbuild/lib/main.js:1493:15)
    at /Users/silveltman/Documents/Github/monorepo-astro/library/node_modules/@bookshop/builder/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/Users/silveltman/Documents/Github/monorepo-astro/library/node_modules/@bookshop/builder/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/Users/silveltman/Documents/Github/monorepo-astro/library/node_modules/@bookshop/builder/node_modules/esbuild/lib/main.js:1149:7)
    at /Users/silveltman/Documents/Github/monorepo-astro/library/node_modules/@bookshop/builder/node_modules/esbuild/lib/main.js:1258:14
    at /Users/silveltman/Documents/Github/monorepo-astro/library/node_modules/@bookshop/builder/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/silveltman/Documents/Github/monorepo-astro/library/node_modules/@bookshop/builder/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/silveltman/Documents/Github/monorepo-astro/library/node_modules/@bookshop/builder/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      location: null,
      notes: [],
      pluginName: '',
      text: 'Cannot use the "file" loader without an output path'
    }
  ],
  warnings: []
```

even with the most basic setup

**Comment by bglw** [comment]
Interesting! I'll look at this in the week.

**Comment by bglw** [comment]
Hey Sil — a release has landed today which hopefully resolves things for you!

https://github.com/CloudCannon/bookshop/releases/tag/v3.8.2

Give that a crack and let me know if not 🙂

**Comment by silveltman** [comment]
Works now ✅
